sudo: false
language:
- node_js
node_js:
- "6"
env:
- ACTION=test
- ACTION="run lint"
- ACTION="run cs-check"
- ACTION="run dist"
script:
- npm $ACTION
- node --harmony_proxies node_modules/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js